"""Email delivery for intelligence briefs.

send_brief() is the single public entry point. It reads SMTP config from
environment variables and degrades gracefully to a file write if any required
variable is absent — the graph must never abort due to a missing email config.

Env vars consumed (all optional — absence triggers file fallback):
  SMTP_HOST, SMTP_PORT (default 587), SMTP_USER, SMTP_PASSWORD, ALERT_TO_EMAIL
"""

from __future__ import annotations

import asyncio
import os
import re
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

import structlog

from pipelineradar.schemas import GroundedBrief

log: structlog.stdlib.BoundLogger = structlog.get_logger(__name__)

_OUTPUT_DIR = Path("output")


async def send_brief(grounded: GroundedBrief, markdown: str, run_id: str) -> None:
    """Send the brief by email, writing to output/ if SMTP is not configured."""
    smtp_host: str | None = os.environ.get("SMTP_HOST")
    smtp_port_str: str = os.environ.get("SMTP_PORT", "587")
    smtp_user: str | None = os.environ.get("SMTP_USER")
    smtp_password: str | None = os.environ.get("SMTP_PASSWORD")
    alert_to: str | None = os.environ.get("ALERT_TO_EMAIL")

    n_items = _count_cited_items(grounded)
    date_str = grounded.generated_at.strftime("%Y-%m-%d")
    subject = (
        f"PipelineRadar · {grounded.therapeutic_area}"
        f" · {n_items} new items · {date_str}"
    )

    if not (smtp_host and smtp_user and smtp_password and alert_to):
        log.warning(
            "email.smtp_not_configured",
            run_id=run_id,
            missing=[
                k
                for k, v in {
                    "SMTP_HOST": smtp_host,
                    "SMTP_USER": smtp_user,
                    "SMTP_PASSWORD": smtp_password,
                    "ALERT_TO_EMAIL": alert_to,
                }.items()
                if not v
            ],
        )
        _write_fallback(markdown, grounded.therapeutic_area, run_id)
        return

    html_body = _build_html(grounded, markdown)

    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = alert_to

    msg.attach(MIMEText(html_body, "html", "utf-8"))

    ta_slug = grounded.therapeutic_area.replace(" ", "_").lower()
    attach_name = f"brief_{ta_slug}_{run_id}.md"
    attachment = MIMEBase("application", "octet-stream")
    attachment.set_payload(markdown.encode("utf-8"))
    encoders.encode_base64(attachment)
    attachment.add_header("Content-Disposition", "attachment", filename=attach_name)
    msg.attach(attachment)

    try:
        smtp_port = int(smtp_port_str)
        await asyncio.to_thread(
            _smtp_send, smtp_host, smtp_port, smtp_user, smtp_password, alert_to, msg
        )
        log.info("email.sent", run_id=run_id, to=alert_to, subject=subject)
    except Exception as exc:
        log.error("email.send_failed", run_id=run_id, error=str(exc))
        _write_fallback(markdown, grounded.therapeutic_area, run_id)


# ── private ────────────────────────────────────────────────────────────────────


def _count_cited_items(grounded: GroundedBrief) -> int:
    seen: set[str] = set()
    for section in grounded.sections:
        for claim in section.claims:
            for cit in claim.citations:
                seen.add(cit.item_id)
    return len(seen)


def _smtp_send(
    host: str,
    port: int,
    user: str,
    password: str,
    to: str,
    msg: MIMEMultipart,
) -> None:
    with smtplib.SMTP(host, port) as server:
        server.ehlo()
        server.starttls()
        server.login(user, password)
        server.sendmail(user, [to], msg.as_string())


def _build_html(grounded: GroundedBrief, markdown: str) -> str:
    body_html = _markdown_to_html(markdown)
    return (
        "<!DOCTYPE html>\n"
        "<html>\n"
        "<head>\n"
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width,initial-scale=1">\n'
        "</head>\n"
        '<body style="font-family:Georgia,serif;max-width:700px;margin:0 auto;'
        'padding:24px;color:#222;background:#fff;">\n'
        + body_html
        + "\n"
        '<hr style="border:none;border-top:1px solid #eee;margin-top:32px;">\n'
        '<p style="font-size:0.8em;color:#999;">'
        f"Generated by PipelineRadar · Run {grounded.run_id}"
        "</p>\n"
        "</body>\n"
        "</html>"
    )


def _markdown_to_html(markdown: str) -> str:
    """Minimal markdown-to-HTML for our brief format."""
    lines = markdown.split("\n")
    out: list[str] = []
    in_list = False

    for line in lines:
        # Unverified warning blockquote (two-space indent + "> ")
        if line.startswith("  > "):
            if in_list:
                out.append("</ul>")
                in_list = False
            content = line[4:]
            out.append(
                '<div style="background:#fff3cd;border-left:4px solid #ffc107;'
                'padding:8px 12px;margin:4px 0;font-size:0.9em;border-radius:3px;">'
                f"{content}</div>"
            )
            continue

        if line.startswith("# "):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(
                '<h1 style="color:#1a1a2e;border-bottom:2px solid #0066cc;'
                f'padding-bottom:8px;">{_inline_md(line[2:])}</h1>'
            )
            continue

        if line.startswith("## "):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(
                f'<h2 style="color:#0066cc;margin-top:24px;">{_inline_md(line[3:])}</h2>'
            )
            continue

        if line.startswith("### "):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(
                f'<h3 style="color:#333;margin-top:16px;">{_inline_md(line[4:])}</h3>'
            )
            continue

        if line.strip() == "---":
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append('<hr style="border:none;border-top:1px solid #eee;margin:16px 0;">')
            continue

        if line.startswith("- "):
            if not in_list:
                out.append('<ul style="padding-left:20px;margin:8px 0;">')
                in_list = True
            out.append(f'<li style="margin:6px 0;">{_inline_md(line[2:])}</li>')
            continue

        if in_list:
            out.append("</ul>")
            in_list = False

        if line.strip():
            out.append(f'<p style="margin:4px 0;">{_inline_md(line)}</p>')

    if in_list:
        out.append("</ul>")

    return "\n".join(out)


def _inline_md(text: str) -> str:
    """Convert inline bold, links, and footnote references."""
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(
        r"\[([^\]]+)\]\(([^)]+)\)",
        r'<a href="\2" style="color:#0066cc;">\1</a>',
        text,
    )
    text = re.sub(r"\[(\d+)\]", r"<sup><strong>[\1]</strong></sup>", text)
    return text


def _write_fallback(markdown: str, therapeutic_area: str, run_id: str) -> None:
    _OUTPUT_DIR.mkdir(exist_ok=True)
    ta_slug = therapeutic_area.replace(" ", "_").lower()
    path = _OUTPUT_DIR / f"brief_{ta_slug}_{run_id}.md"
    path.write_text(markdown, encoding="utf-8")
    log.info("email.fallback_written", path=str(path))
